apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: tekton-insights
  namespace: gbenhaim-tenant
spec:
  application: insights-content-template-renderer
  params:
  - name: APP_NAME
    value: ccx-data-pipeline
  - name: COMPONENTS
    value: insights-content-template-renderer
  - name: COMPONENTS_W_RESOURCES
    value: insights-content-template-renderer
  - name: COMPONENT_NAME
    value: insights-content-template-renderer
  - name: IQE_PLUGINS
    value: ccx
  - name: IQE_MARKER_EXPRESSION
    value: ""
  - name: IQE_FILTER_EXPRESSION
    value: test_plugin_accessible
  - name: IQE_REQUIREMENTS
    value: ""
  - name: IQE_REQUIREMENTS_PRIORITY
    value: ""
  - name: IQE_TEST_IMPORTANCE
    value: ""
  - name: IQE_CJI_TIMEOUT
    value: 30m
  - name: IQE_ENV
    value: clowder_smoke
  - name: IQE_SELENIUM
    value: "false"
  resolverRef:
    params:
    - name: url
      value: https://github.com/gbenhaim/tekton-insights.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
