apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy
spec:
  configuration:
    exclude:
      - step_image_registries
    include:
      - '@slsa3'
  description: 'Includes rules for levels 1, 2 & 3 of SLSA v0.1.'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
      name: Default
      policy:
      - oci::quay.io/enterprise-contract/ec-release-policy:git-2b201b4@sha256:707df8b83612c2aac35e574e94341c8a88134be820b1edee920dce32084e5449
