apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - persistent_volume_claim.yaml
  - ec-policy.yaml
  - release_plan_admission.yaml
  - release_strategy.yaml
namespace: rh-managed-red-hat-acm-tenant
