---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: mintmaker-release-to-quay
  namespace: mintmaker-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: mintmaker-service
  target: rhtap-releng-tenant
