---
apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: quay-token-maestro-remote-secret
spec:
  secret:
    name: quay-token-secret
    type: kubernetes.io/dockerconfigjson
    linkedTo:
      - serviceAccount:
          reference:
            name: maestro-service-account
  targets:
    - namespace: rhtap-releng-tenant