apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-fbc-policy
spec:
  configuration:
    exclude:
      - cve # The release process separates the catalog from the binaries, so CVEs are the responsibility of the OLM team
      - step_image_registries
      - tasks.required_tasks_found:prefetch-dependencies # prefetch is not required
        # FBC fragments do not produce source containers.
      - source_image.exists
    include:
      - '@redhat'
  description: 'Includes rules for shipping Red Hat FBC fragments'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
      name: Default
      policy:
      - oci::quay.io/enterprise-contract/ec-release-policy:git-cd29f49@sha256:6817c74e8cf290e3812790df26ffaa1e0efa4e0f3490e39259fc61a6d3688fdb
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-fbc-stage-index-policy
spec:
  configuration:
    exclude:
      - cve # The release process separates the catalog from the binaries, so CVEs are the responsibility of the OLM team
      - step_image_registries
      - test.required_tests_passed:fbc-related-image-check # not required for staged index Releases
      - tasks.required_tasks_found:prefetch-dependencies # prefetch is not required
      # FBC fragments do not produce source containers.
      - source_image.exists
    include:
      - '@redhat'
  description: 'Includes rules for shipping Red Hat FBC fragments without tests'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
      name: Default
      policy:
      - oci::quay.io/enterprise-contract/ec-release-policy:git-cd29f49@sha256:6817c74e8cf290e3812790df26ffaa1e0efa4e0f3490e39259fc61a6d3688fdb
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-fbc-stage-index-policy-cnv
spec:
  configuration:
    exclude:
      - cve # The release process separates the catalog from the binaries, so CVEs are the responsibility of the OLM team
      - step_image_registries
      - test.required_tests_passed:fbc-related-image-check # not required for staged index Releases
      - tasks.required_tasks_found:prefetch-dependencies # prefetch is not required
      # FBC fragments do not produce source containers.
      - source_image.exists
      # Stage release can ignore weekday restriction
      - schedule.weekday_restriction
    include:
      - '@redhat'
  description: 'Includes rules for shipping Red Hat FBC fragments without tests'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
      name: Default
      ruleData:
        allowed_registry_prefixes:
          - registry.redhat.io/
          - brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:git-cd29f49@sha256:6817c74e8cf290e3812790df26ffaa1e0efa4e0f3490e39259fc61a6d3688fdb
