apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-fbc-policy
spec:
  configuration:
    exclude:
      - cve # The release process separates the catalog from the binaries, so CVEs are the responsibility of the OLM team
      - step_image_registries
    include:
      - '@redhat'
  description: 'Includes rules for shipping Red Hat FBC fragments'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - data:
        - github.com/enterprise-contract/ec-policies//data
      name: Default
      policy:
        - github.com/enterprise-contract/ec-policies//policy/lib
        - github.com/enterprise-contract/ec-policies//policy/release
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-fbc-stage-index-policy
spec:
  configuration:
    exclude:
      - cve # The release process separates the catalog from the binaries, so CVEs are the responsibility of the OLM team
      - step_image_registries
      - test # some tests may fail when pushing to stage, scope to just fbc-related-image-check after https://issues.redhat.com/browse/HACBS-2656
    include:
      - '@redhat'
  description: 'Includes rules for shipping Red Hat FBC fragments without tests'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - data:
        - github.com/enterprise-contract/ec-policies//data
      name: Default
      policy:
        - github.com/enterprise-contract/ec-policies//policy/lib
        - github.com/enterprise-contract/ec-policies//policy/release
