apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: cloud-connector-tekton-insights
  namespace: hcc-pipeline-tenant
spec:
  application: cloud-connector
  contexts:
  - description: Application testing
    name: application
  params:
  - name: APP_NAME
    value: cloud-connector
  - name: BONFIRE_COMPONENT_NAME
    value: cloud-connector-api
  - name: COMPONENT_NAME
    value: cloud-connector
  - name: IQE_PLUGINS
    value: cloud-connector
  - name: IQE_MARKER_EXPRESSION
    value: not e2e
  - name: IQE_CJI_TIMEOUT
    value: 30m
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsights/bonfire-tekton.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
