apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: mintmaker-renovate-image-release-to-quay
  namespace: konflux-mintmaker-tenant
spec:
  application: mintmaker-renovate-image
  target: rhtap-releng-tenant
