apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rhtap-o11y-rpa
  namespace: rh-managed-rhtap-ser-tenant
spec:
  applications:
  - o11y
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    infra-deployment-update-script: |
      sed -i -e 's|\(https://github.com/redhat-appstudio/o11y/.*?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/monitoring/grafana/base/kustomization.yaml
    mapping:
      components:
      - name: o11y
        repository: quay.io/redhat-appstudio/o11y
    pyxis:
      secret: pyxis-production-secret
      server: production
  origin: rhtap-o11y-tenant
  pipelineRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/release-service-catalog.git
    - name: revision
      value: production
    - name: pathInRepo
      value: pipelines/rhtap-service-push/rhtap-service-push.yaml
    resolver: git
  policy: rh-policy-o11y
  serviceAccount: rhtap-servicerelease-sa
