apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rhtap-build-trusted-artifacts-rpa
  namespace: rh-managed-rhtap-ser-tenant
spec:
  applications:
  - build-trusted-artifacts
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    mapping:
      components:
      - name: build-trusted-artifacts
        repository: quay.io/redhat-appstudio/build-trusted-artifacts
    pyxis:
      secret: pyxis-production-secret
      server: production
    slack:
      slack-notification-secret: build-team-slack-webhook-notification-secret
      slack-webhook-notification-secret-keyname: build
  origin: rhtap-build-tenant
  pipeline:
    pipelineRef:
      params:
      - name: url
        value: https://github.com/konflux-ci/release-service-catalog.git
      - name: revision
        value: production
      - name: pathInRepo
        value: pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
      resolver: git
    serviceAccountName: rhtap-servicerelease-sa
  policy: rh-policy
