apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy-o11y
  namespace: rh-managed-rhtap-ser-tenant
spec:
  configuration:
    exclude:
    - hermetic_build_task
    - step_image_registries
    - tasks.required_tasks_found:prefetch-dependencies
    - attestation_task_bundle.task_ref_bundles_acceptable
    - attestation_task_bundle.tasks_defined_in_bundle
    include:
    - '@redhat'
  description: A special reduced ruleset for Observability.
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
    name: Release Policies
    policy:
    - oci::quay.io/enterprise-contract/ec-release-policy:git-8852970@sha256:24e577c6d8fb2d8bc103c69d2625243edce205a8b4c135a80ba600a4739c74eb
