apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rhtap-image-controller-rpa
  namespace: rh-managed-rhtap-ser-tenant
spec:
  applications:
  - image-controller
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    infra-deployment-update-script: |
      sed -i -e 's|\(https://github.com/redhat-appstudio/image-controller/config/default?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/image-controller/development/kustomization.yaml
      sed -i -e 's|\(https://github.com/redhat-appstudio/image-controller/config/default?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/image-controller/staging/kustomization.yaml
    mapping:
      components:
      - name: image-controller
        repository: quay.io/redhat-appstudio/image-controller
    pyxis:
      secret: pyxis-production-secret
      server: production
    slack:
      slack-notification-secret: build-team-slack-webhook-notification-secret
      slack-webhook-notification-secret-keyname: build
  origin: rhtap-build-tenant
  pipelineRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/release-service-catalog.git
    - name: revision
      value: production
    - name: pathInRepo
      value: pipelines/rhtap-service-push/rhtap-service-push.yaml
    resolver: git
  policy: rh-policy
  serviceAccount: rhtap-servicerelease-sa
