apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy-release-service
  namespace: rh-managed-rhtap-ser-tenant
spec:
  configuration:
    exclude:
    - hermetic_build_task
    - step_image_registries
    - tasks.required_tasks_found:prefetch-dependencies
    include:
    - '@redhat'
  description: Includes rules for levels 1, 2 & 3 of SLSA v0.1.
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
    name: Release Policies
    policy:
    - oci::quay.io/enterprise-contract/ec-release-policy:git-8229928@sha256:0e697db0d42416a23a58cc52597057dd12f7eb71bd8930c95564706126c15df6
