---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: consoledot-frontend-standard
  namespace: rhtap-releng-tenant
spec:
  configuration:
    include:
      - '@redhat'
    exclude:
      - base_image_registries.base_image_permitted
      - labels.disallowed_inherited_labels
      - tasks.required_tasks_found:source-build
      - test.no_skipped_tests:sast-snyk-check
      - hermetic_build_task.build_task_hermetic
      - attestation_task_bundle.tasks_defined_in_bundle
      - tasks.required_tasks_found:prefetch-dependencies
      # for testing purposes
      - tasks.pinned_task_refs
  description: 'Includes rules to set a standard for current App Interface deployments'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:git-2b201b4@sha256:707df8b83612c2aac35e574e94341c8a88134be820b1edee920dce32084e5449
