apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy
spec:
  configuration:
    exclude:
      - hermetic_build_task # Change policy definition once https://issues.redhat.com/browse/HACBS-2657 is implemented
      - step_image_registries
      - tasks.required_tasks_found:prefetch-dependencies # prefetch is not required
      - test.required_tests_passed:sast-snyk-check # requirement is for snyk to run, not to pass
    include:
      - '@redhat'
  description: 'Includes rules for levels 1, 2 & 3 of SLSA v0.1.'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
      name: Default
      policy:
      - oci::quay.io/enterprise-contract/ec-release-policy:git-fbe4116@sha256:d493c08361a6713fc4068139996bf87d2d1d1d5f0fea8209878539b62f5b7b18
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: app-interface-standard
spec:
  configuration:
    include:
      - '@redhat'
    exclude:
      # Currently, App Interface teams are not requiring CVEs checks 
      # to deploy
      - cve
      # prefetch is not required
      - tasks.required_tasks_found:prefetch-dependencies
      # we are not forcing them to pass snyk test yet
      - test.required_tests_passed:sast-snyk-check
      - test.no_skipped_tests:sast-snyk-check
      # hermetic build is not required yet
      - hermetic_build_task
      # we don't need teams to update the labels for the first migration
      - labels.disallowed_inherited_labels
  description: 'Includes rules to set a standard for current App Interface deployments'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:git-fbe4116@sha256:d493c08361a6713fc4068139996bf87d2d1d1d5f0fea8209878539b62f5b7b18
