apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: build-service-release-to-quay-rhtap-ser
  namespace: rhtap-build-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: build-service
  target: rhtap-releng-tenant
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: image-controller-release-to-quay-rhtap-ser
  namespace: rhtap-build-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: image-controller
  target: rhtap-releng-tenant
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: multi-platform-controller-release-to-quay-rhtap-ser
  namespace: rhtap-build-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: multi-platform-controller
  target: rhtap-releng-tenant
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: trusted-artifacts-to-quay-rhtap-ser
  namespace: rhtap-build-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: trusted-artifacts
  target: rhtap-releng-tenant
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: rh-syft-registry-redhat-io
  namespace: rhtap-build-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'false'
spec:
  application: rh-syft
  target: rhtap-releng-tenant
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: source-container-build-release-to-quay-rhtap-ser
  namespace: rhtap-build-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: build-tasks-dockerfiles
  target: rhtap-releng-tenant
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: buildah-container
  namespace: rhtap-build-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: buildah-container
  target: rhtap-releng-tenant
