apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: konflux-servicerelease-rb
  namespace: rhtap-releng-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
  - kind: ServiceAccount
    name: konflux-servicerelease-sa
    namespace: rhtap-releng-tenant
  - kind: ServiceAccount
    name: konflux-ci-servicerelease-sa
    namespace: rhtap-releng-tenant
