apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maestro-service-account
  namespace: rhtap-releng-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
  - kind: ServiceAccount
    name: maestro-service-account
    namespace: rhtap-releng-tenant
