apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy
  namespace: rh-managed-red-hat-acm-tenant
spec:
  configuration:
    exclude:
    - step_image_registries
    include:
    - '@slsa1'
    - '@slsa2'
    - '@slsa3'
  description: Includes rules for levels 1, 2 & 3 of SLSA v0.1.
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
    name: Default
    policy:
    - oci::quay.io/enterprise-contract/ec-release-policy:git-2f48179@sha256:ba89f48bfac5750e9e105e4d158f371c99fd8d407090cd1cdcfba9ebb1c6549e
