apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: hypershift-operator-rpa
  namespace: rh-managed-red-hat-acm-tenant
spec:
  application: hypershift-operator
  origin: crt-redhat-acm-tenant
  releaseStrategy: push-to-external-registry-strategy
