apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false" # Change to "true" if you don't need the test to be mandatory
  name: pulp-bonfire-tekton
  namespace: pulp-services-tenant
spec:
  application: pulp
  resolverRef:
    params:
    - name: url
      value: https://github.com/pulp/pulp-service.git
    - name: revision
      value: main
    - name: pathInRepo
      value: .tekton/pulp-deploy-and-test.yaml
    resolver: git
  params:
    - name: APP_NAME
      value: "pulp"
    - name: COMPONENTS
      value: # Space-separated list of components to load.
    - name: COMPONENTS_W_RESOURCES
      value: "pulp"
    - name: BONFIRE_COMPONENT_NAME
      value: # Name of app-sre "resourceTemplate" in deploy.yaml for this component. If it is the same as the name in Konflux, you don't need to fill this
    - name: COMPONENT_NAME
      value: "pulp"
    - name: EXTRA_DEPLOY_ARGS # This wasn't in the documentation, but in the bonfire-tekton code
      value: "--set-parameter pulp/PULP_API_MEMORY_LIMIT=4096Mi --set-parameter pulp/PULP_API_MEMORY_REQUEST=2048Mi provisioning sources image-builder-crc"
