apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: api-frontend-enterprise-contract
  namespace: rh-platform-experien-tenant
spec:
  application: api-frontend
  contexts:
  - description: Application testing
    name: application
  params:
  - name: POLICY_CONFIGURATION
    value: rhtap-releng-tenant/consoledot-frontend-standard
  resolverRef:
    params:
    - name: url
      value: https://github.com/konflux-ci/build-definitions
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/enterprise-contract.yaml
    resolver: git
