apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: ecosystem-images-release-as-op
  namespace: tekton-ecosystem-tenant
spec:
  application: ecosystem-images
  target: rhtap-releng-tenant
