apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-pvc
  namespace: rh-managed-red-hat-acm-tenant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
