apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: release-to-quay
  namespace: rhtap-build-tenant
spec:
  application: build
  displayName: build release-to-quay
  target: rhtap-servicerelease-tenant
