apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: ols-enterprise-contract
  namespace: crt-nshift-lightspeed-tenant
spec:
  application: ols
  contexts:
  - description: Application testing
    name: application
  resolverRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/build-definitions
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/enterprise-contract.yaml
    resolver: git
