apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: registry-redhat-io-quay-token-secret-remote-secret
  namespace: managed-release-team-tenant
spec:
  secret:
    name: quay-token-secret
    type: kubernetes.io/dockerconfigjson
    linkedTo:
      - serviceAccount:
          reference:
            name: rh-push-to-registry-redhat-io-sa
  targets:
    - namespace: managed-release-team-tenant
