apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: o11y-enterprise-contract
  namespace: rhtap-o11y-tenant
spec:
  application: o11y
  contexts:
  - description: Application testing
    name: application
  params:
  - name: POLICY_CONFIGURATION
    value: rh-managed-rhtap-ser-tenant/rh-policy-o11y
  resolverRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/build-definitions
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/enterprise-contract.yaml
    resolver: git
