apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: tools-release-to-quay-konflux-ser
  namespace: rhtap-o11y-tenant
spec:
  application: tools
  target: rhtap-releng-tenant
