apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true" # Change to "true" if you don't need the test to be mandatory
  name: platform-feedback-bonfire-tekton
  namespace: hcc-accessmanagement-tenant
spec:
  application: platform-feedback
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsigths/bonfire-tekton.git
    - name: revision
      value: main # Or whatever branch you want to test
    - name: pathInRepo
      value: pipelines/basic.yaml # This is the path to the pipeline
    resolver: git
  params:
    - name: APP_NAME
      value: platform-feedback
    - name: COMPONENT_NAME
      value: platform-feedback
