apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: payload-tracker-frontend-enterprise-contract
  namespace: hcc-pipeline-tenant
spec:
  params: 
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/consoledot-frontend-standard
  application: payload-tracker-frontend
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/konflux-ci/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git