apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: storage-broker-enterprise-contract
  namespace: hcc-pipeline-tenant
spec:
  application: storage-broker
  contexts:
    - description: Application testing
      name: application
  params:
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/app-interface-standard
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/redhat-appstudio/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
