apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy
spec:
  configuration:
    exclude:
      - hermetic_build_task # Change policy definition once https://issues.redhat.com/browse/HACBS-2657 is implemented
        # Exclude step_image_registries for now since it can cause false
        # positives due to https://issues.redhat.com/browse/OCPBUGS-8428
      - step_image_registries
      - tasks.required_tasks_found:prefetch-dependencies # prefetch is not required
    include:
      - '@redhat'
  description: 'Includes rules for levels 1, 2 & 3 of SLSA v0.1.'
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:git-9e347db@sha256:209d9d4c629e6caf5b6c1e94206969555192fbc6e2385d26c440607b7bc63cf7
