apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: assisted-service-saas-hotfix
  namespace: assisted-installer-tenant
spec:
  application: assisted-service-saas-hotfix
  componentName: assisted-service-saas-hotfix
  skipGitOpsResourceGeneration: true
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile.assisted-service
      revision: cloud_hotfix_releases
      url: https://github.com/openshift/assisted-service.git
