apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: bootc-c9s
  namespace: rh-managed-bifrost-tenant
spec:
  applications:
  - bootc-c9s
  data:
    images:
      addGitShaTag: true
      floatingTags:
      - stream9
      - c9s
    mapping:
      components:
      - name: centos-bootc-c9s
        repository: quay.io/centos-bootc/centos-bootc
      - name: bootc-image-builder-c9s
        repository: quay.io/centos-bootc/bootc-image-builder
  origin: centos-bootc-tenant
  pipeline:
    pipelineRef:
      params:
      - name: url
        value: https://github.com/konflux-ci/release-service-catalog.git
      - name: revision
        value: production
      - name: pathInRepo
        value: pipelines/push-to-external-registry/push-to-external-registry.yaml
      resolver: git
    serviceAccountName: release-sa-centos-bootc
  policy: rh-policy
