apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy
  namespace: rh-managed-bifrost-tenant
spec:
  configuration:
    exclude:
    - hermetic_build_task
    - step_image_registries
    - tasks.required_tasks_found:prefetch-dependencies
    - sbom_cyclonedx
    include:
    - '@minimal'
    - '@slsa3'
  description: Rules specifically related to levels 1, 2 & 3 of SLSA v0.1, plus a
    set of basic checks that are expected to pass for all RHTAP builds. Available
    collections are defined in https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/release_policy.html#_available_rule_collections.
    If a different policy configuration is desired, this resource can serve as a starting
    point. See the docs on how to include and exclude rules https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/policy_configuration.html#_including_and_excluding_rules.
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
    name: Release Policies
    policy:
    - oci::quay.io/enterprise-contract/ec-release-policy:git-8229928@sha256:0e697db0d42416a23a58cc52597057dd12f7eb71bd8930c95564706126c15df6
    ruleData:
      allowed_registry_prefixes:
      - registry.access.redhat.com/
      - registry.redhat.io/
      - brew.registry.redhat.io/rh-osbs/openshift-golang-builder
      - localhost/rhtap-final-image
      - registry.fedoraproject.org/fedora
      restrict_cve_security_levels:
      - critical
      warn_cve_security_levels:
      - high
