apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: rhtap-service-push-strategy
  namespace: rhtap-servicerelease-tenant
spec:
  bundle: quay.io/hacbs-release/pipeline-rhtap-service-push:main
  params:
  - name: extraConfigGitUrl
    value: https://github.com/hacbs-release/strategy-configs.git
  - name: extraConfigPath
    value: rhtap.yaml
  - name: extraConfigRevision
    value: main
  - name: pyxisServerType
    value: stage
  - name: pyxisSecret
    value: pyxis-staging-secret
  - name: tag
    value: latest
  - name: addGitShaTag
    value: "true"
  pipeline: rhtap-service-push
  policy: rh-policy
  serviceAccount: rhtap-servicerelease-sa
