apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: rhtap-build-rpa
  namespace: rhtap-servicerelease-tenant
spec:
  application: build
  displayName: ""
  extraData:
    infra-deployment-update-script: |
      sed -i -e 's|\(https://github.com/redhat-appstudio/image-controller/.*?ref=\)\(.*\)|\1{{ revision }} |' -e 's/\(newTag: \).*/\1{{ revision }}/' components/image-controller/base/kustomization.yaml
    slack-webhook-notification-secret-keyname: build
  origin: rhtap-build-tenant
  releaseStrategy: rhtap-service-push-strategy
