apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: io-gathering-service-bonfire-tekton
  namespace: obsint-processing-tenant
spec:
  application: io-gathering-service
  contexts:
  - description: Application testing
    name: application
  params:
  - name: APP_NAME
    value: ccx-data-pipeline
  - name: REV_ENV
    value: insights-production
  - name: COMPONENTS
    value: io-gathering-service
  - name: COMPONENTS_W_RESOURCES
    value: io-gathering-service
  - name: BONFIRE_COMPONENT_NAME
    value: io-gathering-service
  - name: COMPONENT_NAME
    value: io-gathering-service
  - name: IQE_PLUGINS
    value: ccx
  - name: IQE_MARKER_EXPRESSION
    value: io_gathering
  - name: IQE_FILTER_EXPRESSION
    value: null
  - name: IQE_REQUIREMENTS
    value: null
  - name: IQE_REQUIREMENTS_PRIORITY
    value: null
  - name: IQE_TEST_IMPORTANCE
    value: null
  - name: IQE_CJI_TIMEOUT
    value: 60m
  - name: IQE_ENV
    value: null
  - name: IQE_ENV_VARS
    value: DYNACONF_USER_PROVIDER__rbac_enabled=false
  - name: IQE_SELENIUM
    value: null
  - name: IQE_PARALLEL_ENABLED
    value: null
  - name: IQE_PARALLEL_WORKER_COUNT
    value: null
  - name: IQE_RP_ARGS
    value: null
  - name: IQE_IBUTSU_SOURCE
    value: null
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsights/bonfire-tekton.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
