apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy
spec:
  configuration:
    exclude:
      - hermetic_build_task # Change policy definition once https://issues.redhat.com/browse/HACBS-2657 is implemented
        # Exclude step_image_registries for now since it can cause false
        # positives due to https://issues.redhat.com/browse/OCPBUGS-8428
      - step_image_registries
      - tasks.required_tasks_found:prefetch-dependencies # prefetch is not required
      # Currently using a non-standard buildah task that does not push an SBOM
      - sbom_cyclonedx
    include:
        - '@minimal'
        - '@slsa3'
  description: >-
    Rules specifically related to levels 1, 2 & 3 of SLSA v0.1, plus a set of
    basic checks that are expected to pass for all RHTAP builds. Available
    collections are defined in
    https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/release_policy.html#_available_rule_collections.
    If a different policy configuration is desired, this resource can serve as a
    starting point. See the docs on how to include and exclude rules
    https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/policy_configuration.html#_including_and_excluding_rules.
  publicKey: 'k8s://openshift-pipelines/public-key'
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:git-8f22774@sha256:f887fb71d95ebe45703917da60770580035e9158b26b89e56efbba05474f6ec2
      ruleData:
        allowed_registry_prefixes:
          # These are the defaults
          - registry.access.redhat.com/
          - registry.redhat.io/
          - brew.registry.redhat.io/rh-osbs/openshift-golang-builder
          # Custom addition to permit localhost/rhtap-final-image as a base image
          - localhost/rhtap-final-image
          # Custom addition to permit registry.fedoraproject.org/fedora as a base image
          - registry.fedoraproject.org/fedora
        # Currently there are four high severity CVEs that aren't practical to fix
        # in the short term. Configure 'high' severity CVEs to be warnings instead of
        # violations. The default values are:
        #  restrict_cve_security_levels: [critical, high]
        #  warn_cve_security_levels: []
        restrict_cve_security_levels: [critical]
        warn_cve_security_levels: [high]
