apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-fbc-stage-index-policy
  namespace: rh-managed-cnv-fbc-tenant
spec:
  configuration:
    exclude:
    - cve
    - step_image_registries
    - test.required_tests_passed:fbc-related-image-check
    - tasks.required_tasks_found:prefetch-dependencies
    include:
    - '@redhat'
  description: Includes rules for shipping Red Hat FBC fragments without tests
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
    name: Default
    policy:
    - oci::quay.io/enterprise-contract/ec-release-policy:git-2f48179@sha256:ba89f48bfac5750e9e105e4d158f371c99fd8d407090cd1cdcfba9ebb1c6549e
    - github.com/enterprise-contract/ec-policies//policy/release
