apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: platform-feedback-bonfire-tekton
  namespace: hcc-accessmanagement-tenant
spec:
  application: platform-feedback
  params:
  - name: APP_NAME
    value: platform-feedback
  - name: COMPONENT_NAME
    value: platform-feedback
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsigths/bonfire-tekton.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
