apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: rh-trex-release-to-quay
  namespace: rh-trex-tenant
spec:
  application: rh-trex
  target: rh-trex-tenant
