apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: quay-token-maestro-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: maestro-service-account
    name: quay-token-secret
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: rhtap-releng-tenant
