apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-pipelines
  namespace: rhtap-releng-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
- kind: ServiceAccount
  name: release-registry-prod
  namespace: rhtap-releng-tenant
- kind: ServiceAccount
  name: release-registry-staging
  namespace: rhtap-releng-tenant
- kind: ServiceAccount
  name: release-registry-dev
  namespace: rhtap-releng-tenant
- kind: ServiceAccount
  name: release-index-image-prod
  namespace: rhtap-releng-tenant
- kind: ServiceAccount
  name: release-index-image-staging
  namespace: rhtap-releng-tenant
- kind: ServiceAccount
  name: release-app-interface-prod
  namespace: rhtap-releng-tenant
- kind: ServiceAccount
  name: release-app-interface-staging
  namespace: rhtap-releng-tenant
- kind: ServiceAccount
  name: release-github-terraform-prod
  namespace: rhtap-releng-tenant
- kind: ServiceAccount
  name: release-github-terraform-dev
  namespace: rhtap-releng-tenant
