---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: centos-bootc
  namespace: rh-managed-bifrost-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - centos-bootc
  data:
    images:
      addGitShaTag: true
      floatingTags:
        - stream9
    mapping:
      components:
        - name: centos-bootc
          repository: "quay.io/centos-bootc/centos-bootc"
  origin: centos-bootc-tenant
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/push-to-external-registry/push-to-external-registry.yaml"
    serviceAccountName: release-sa-centos-bootc
  policy: rh-policy
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: centos-bootc-c9s
  namespace: rh-managed-bifrost-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - bootc-c9s
  data:
    images:
      addGitShaTag: true
      floatingTags:
        - stream9
        - c9s
    mapping:
      components:
        - name: centos-bootc-c9s
          repository: "quay.io/centos-bootc/centos-bootc"
  origin: centos-bootc-tenant
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/push-to-external-registry/push-to-external-registry.yaml"
    serviceAccountName: release-sa-centos-bootc
  policy: rh-policy
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: centos-bootc-c10s
  namespace: rh-managed-bifrost-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - centos-bootc-c10s
  data:
    images:
      addGitShaTag: true
      floatingTags:
        - stream10
        - c10s
    mapping:
      components:
        - name: centos-bootc-c10s
          repository: "quay.io/centos-bootc/centos-bootc"
  origin: centos-bootc-tenant
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/push-to-external-registry/push-to-external-registry.yaml"
    serviceAccountName: release-sa-centos-bootc
  policy: rh-policy
