---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: assisted-installer
spec:
  applications:
    - assisted-events-scrape
    - assisted-events-stream
    - assisted-image-service
    - assisted-service
    - prow-jobs-scraper
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    mapping:
      components:
        - name: assisted-events-scrape-uzau
          repository: "quay.io/rhtap-managed-services/assisted-installer-assisted-events-scrape"
        - name: assisted-events-stream-e1fd
          repository: "quay.io/rhtap-managed-services/assisted-installer-assisted-events-stream"
        - name: assisted-image-service-g1ho
          repository: "quay.io/rhtap-managed-services/assisted-installer-assisted-image-service"
        - name: assisted-service-q2vh
          repository: "quay.io/rhtap-managed-services/assisted-installer-assisted-service"
        - name: prow-jobs-scraper-xg3v
          repository: "quay.io/rhtap-managed-services/assisted-installer-prow-jobs-scraper"
        - name: cicd-tools
          repository: "quay.io/rhtap-managed-services/rhtap-migration-bonfire-cicd-tools"
    pyxis:
      secret: pyxis-staging-secret
      server: stage
  origin: assisted-installer-tenant
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/redhat-appstudio/release-service-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/push-to-external-registry/push-to-external-registry.yaml"
  policy: rh-policy
  serviceAccount: release-service-account
