apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "false"
    release.appstudio.openshift.io/releasePlanAdmission: operator-fbc-prod-index
    release.appstudio.openshift.io/standing-attribution: "true"
  name: fbc-v4-14-release-as-production-fbc
  namespace: orchestrator-releng-tenant
spec:
  application: fbc-v4-14
  target: rhtap-releng-tenant
